name: content-init

# This workflow is triggered on push to the 'content-web' directory of the main branch of the repository
on:
  push:
    branches:
    - main
    paths:
    - 'content-init/**'

  # Configure workflow to also support triggering manually
  workflow_dispatch:

# Environment variables are defined so that they can be used throughout the job definitions.
env:
  imageRepository: 'content-init'
  resourceGroupName: 'Fabmedical-solvidal'
  containerRegistryName: 'fabmedicalial'
  containerRegistry: 'fabmedicalial.azurecr.io'
  dockerfilePath: './content-init'
  tag: '${{ github.run_id  }}'

# Jobs define the actions that take place when code is pushed to the main branch
jobs:

  build-and-publish-docker-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
    # Checkout the repo
    - uses: actions/checkout@master

    - name: Build and push an image to container registry
      uses: docker/build-push-action@v1
      with:
        username: 'fabmedicalial'
        password: 'ZgWf4+etntOPeW7oR+LQwHoRWU6zhnOJ2zXL+krSeg+ACRAIHQ/8'
        path: ${{ env.dockerfilePath  }}
        dockerfile: '${{ env.dockerfilePath }}/Dockerfile'
        registry: ${{ env.containerRegistry }}
        repository: ${{ env.imageRepository }}
        tags: ${{ env.tag }},latest
